const data = {
  product: [
    {
      name: "chealse-shoes",
      slug: "chealse-shoes",
      category: "shoes",
      image: "/image/1.jpg",
      price: 45,
      countInStock: 7,
      brand: "molianseng",
      rating: 4.1,
      numReviews: 17,
      description: "high quality shoes",
    },
    {
      name: "Air max",
      slug: "Air-max",
      category: "shoes",
      image: "/image/c91f9667-423a-48bc-9f7a-8331a3817325.webp",
      price: 85,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 27,
      description: "high quality shoes",
    },
    {
      name: "Busenitz men shoes",
      slug: "Busenitz-men-shoes",
      category: "shoes",
      image: "/image/adidas-Busenitz-White-Collegiate-Green.jpg",
      price: 105,
      countInStock: 5,
      brand: "adidas",
      rating: 4.4,
      numReviews: 22,
      description: "high quality shoes",
    },
    {
      name: "Superstar XLG Shoes. Men's",
      slug: "Superstar-XLG-Shoes-Men",
      category: "shoes",
      image: "/image/Superstar_XLG_Shoes_Black_IG9777_01_standard.avif",
      price: 50,
      countInStock: 15,
      brand: "adidas",
      rating: 4.0,
      numReviews: 18,
      description: "high quality shoes",
    },
  ],
};

export default data;
